### ISSUE TITLE
The plugin "deno-resolver" didn't set a resolve directory, so esbuild did not search for "\\main.ts" on the file system.

### ISSUE THREAD

**Issue by ooker777** [mattvr/dsbuild#1]
```
dsbuild --in .\main.ts --out test.js
Building...
✘ [ERROR] Could not resolve "\\QC supplements\\Code\\Apps\\Tr%E1%BA%A5n K%E1%BB%B3\\B X%E1%BB%AD l%C3%BD d%E1%BB%AF li%E1%BB%87u v%C3%A0 %C4%91%E1%BA%A9y l%C3%AAn Fibery\\main.ts" [plugin deno-resolver]

  The plugin "deno-resolver" didn't set a resolve directory, so esbuild did not search for "\\QC
  supplements\\Code\\Apps\\Tr%E1%BA%A5n K%E1%BB%B3\\B X%E1%BB%AD l%C3%BD d%E1%BB%AF li%E1%BB%87u
  v%C3%A0 %C4%91%E1%BA%A9y l%C3%AAn Fibery\\main.ts" on the file system.

Error: Build failed with 1 error:
error: Could not resolve "\\QC supplements\\Code\\Apps\\Tr%E1%BA%A5n K%E1%BB%B3\\B X%E1%BB%AD l%C3%BD d%E1%BB%AF li%E1%BB%87u v%C3%A0 %C4%91%E1%BA%A9y l%C3%AAn Fibery\\main.ts"
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.18.11/mod.js:1615:15)
    at https://deno.land/x/esbuild@v0.18.11/mod.js:1027:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.18.11/mod.js:1450:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.18.11/mod.js:1025:7)
    at https://deno.land/x/esbuild@v0.18.11/mod.js:1037:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (https://deno.land/x/esbuild@v0.18.11/mod.js:1036:54)
    at handleRequest (https://deno.land/x/esbuild@v0.18.11/mod.js:702:19)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.18.11/mod.js:724:7)
    at readFromStdout (https://deno.land/x/esbuild@v0.18.11/mod.js:652:7) {
  errors: [
    {
      detail: undefined,
      id: "",
      location: null,
      notes: [
        {
          location: null,
          text: `The plugin "deno-resolver" didn't set a resolve directory, so esbuild did not search for "\\\\QC suppl`... 160 more characters
        }
      ],
      pluginName: "deno-resolver",
      text: 'Could not resolve "\\\\QC supplements\\\\Code\\\\Apps\\\\Tr%E1%BA%A5n K%E1%BB%B3\\\\B X%E1%BB%AD l%C3%BD d%E1%'... 69 more characters
    }
  ],
  warnings: []
}
```
Do you have any idea?

**Comment by mattvr** [comment]
Hey @ooker777, sorry for the long delay, I just saw this.

I've just fixed Windows support in the latest version. Could you give it a try?

**Comment by ooker777** [comment]
Hi. The project has been moving passed this long ago and I no longer needing this. When I have the time to look back I'll try it again. Thanks.

**Comment by mattvr** [comment]
Thank you. I will close this for now.
